
-- Chat Colors

HSK_COLOR_RED     = "|cFFFF0000"
HSK_COLOR_GREEN   = "|cFF00FF00"
HSK_COLOR_BLUE    = "|cFF0000FF"
HSK_COLOR_YELLOW  = "|cFFFFFF00"
HSK_COLOR_CYAN    = "|cFF00FFFF"
HSK_COLOR_ORANGE  = "|cFFFF8C00"
HSK_COLOR_PINK    = "|cFFFF69B4"
HSK_COLOR_DEFAULT = "|r"
